name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Install Dependencies (non-Linux)
      if: matrix.os != 'ubuntu-latest'
      run: npm ci
      
    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npm install
    
    - name: Create certificates directory
      run: mkdir -p certificates
      
    - name: Create empty certificate files for build
      run: |
        touch certificates/entitlements.plist
        echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict></dict></plist>' > certificates/entitlements.plist
        echo 'module.exports = async function (params) { console.log("Notarization skipped"); };' > certificates/notarize.js
    
    - name: Set permissions for app-builder
      if: matrix.os == 'ubuntu-latest'
      run: chmod +x node_modules/app-builder-bin/linux/x64/app-builder
    
    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: npx electron-builder build --win --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: npx electron-builder build --mac --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: npx electron-builder build --linux --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-windows-latest
        path: dist/windows
        
    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-macos-latest
        path: dist/macos
        
    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-ubuntu-latest
        path: dist/linux
    
    - name: Display artifacts structure
      run: ls -R dist/
    
    - name: Extract version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/windows/**/*.exe
          dist/macos/**/*.dmg
          dist/linux/**/*.deb
          dist/linux/**/*.AppImage
        draft: false
        prerelease: false
        name: OpenMC Username Sniper v${{ steps.get_version.outputs.version }}
        body: |
          ## OpenMC Username Sniper v${{ steps.get_version.outputs.version }}
          
          ### Changes in this release:
          - First official release of the OpenMC Username Sniper
          - Modern UI with dark and light themes
          - Cross-platform support (Windows, macOS, Linux)
          - Username checking, monitoring, and claiming functionality
          - Batch processing for multiple usernames
          - Smart scheduling for upcoming username drops
          - Notification system (desktop, Discord, email)
          
          ### Download for your platform:
          - Windows: OpenMC-Username-Sniper-Setup-Windows.exe
          - macOS: OpenMC-Username-Sniper-macOS.dmg
          - Linux (deb): openmc-username-sniper_linux.deb
          - Linux (AppImage): openmc-username-sniper_linux.AppImage
          
          See the [README](https://github.com/shaw-llc/Minecraft-Sniper-Application/blob/master/README-APP.md) for installation instructions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 